# Generated by Django 4.1.1 on 2022-09-29 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hospede",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome_do_hospede",
                    models.CharField(
                        help_text="Insira o nome do hóspede", max_length=50
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Feminino")], max_length=1
                    ),
                ),
                ("data_de_admissao", models.DateField(blank=True, null=True)),
                ("n_de_matricula", models.CharField(max_length=12)),
                ("data_desligamento_obito", models.DateField(blank=True, null=True)),
                ("nascimento", models.DateField(blank=True, null=True)),
            ],
            options={"ordering": ["nome_do_hospede"],},
        ),
        migrations.CreateModel(
            name="Familiar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Insira o nome do hóspede", max_length=50
                    ),
                ),
                ("data_de_nascimento", models.DateField(blank=True, null=True)),
                ("parentesco_vinculo", models.CharField(max_length=20)),
                (
                    "hospede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="betel.hospede"
                    ),
                ),
            ],
            options={"ordering": ["hospede", "nome"],},
        ),
    ]
