# Generated by Django 4.1.1 on 2022-09-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betel", "0002_alter_hospede_n_de_matricula_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospede",
            name="n_de_matricula",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="hospede",
            name="nome_do_hospede",
            field=models.CharField(
                blank=True,
                help_text="Insira o nome do hóspede",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hospede",
            name="sexo",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculino"), ("F", "Feminino")],
                max_length=1,
                null=True,
            ),
        ),
    ]
