# Generated by Django 4.1.1 on 2022-09-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betel", "0003_alter_hospede_n_de_matricula_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hospede",
            name="assistente_social",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="certidao_de_nascimento_folha",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="certidao_de_nascimento_livro",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="condicoes_de_moradia",
            field=models.CharField(
                blank=True,
                choices=[("P", "Própria"), ("A", "Alugada"), ("C", "Cedida")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="cor_raca",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BR", "Branca"),
                    ("PR", "Preta"),
                    ("AM", "Amarela"),
                    ("PA", "Parda"),
                    ("IN", "Indígena"),
                    ("SD", "Sem Declaração"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="cpf",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="data_de_preenchimento_da_ficha",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="demanda_apresentada_orientacoes_encaminhamentos",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="endereco_bairro",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="endereco_cep",
            field=models.CharField(
                blank=True, help_text="Formato: 00000-000", max_length=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="endereco_complemento",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="endereco_distrito",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="endereco_numero",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="endereco_rua",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="estado_civil",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SO", "Solteiro(a)"),
                    ("CA", "Casado(a)"),
                    ("SE", "Separado(a)"),
                    ("DI", "Divorciado(a)"),
                    ("VI", "Viúvo(a)"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="estado_profissional",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EM", "Empregado(a)"),
                    ("DE", "Desempregado(a)"),
                    ("AP", "Aposentado(a)"),
                    ("PE", "Pensionista"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="grau_de_instrucao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EFI", "Ensino Fundamental Incompleto"),
                    ("EFC", "Ensino Fundamental Completo"),
                    ("EMI", "Ensino Médio Incompleto"),
                    ("EMC", "Ensino Médio Completo"),
                    ("ESI", "Ensino Superior Incompleto"),
                    ("ESC", "Ensino Superior Completo"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="grau_de_parentesco",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="idoso_recebe_auxilio_para_custo_de_despesas",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="mae",
            field=models.CharField(
                help_text="Insira o nome da mãe", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="motivo_da_hospedagem",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AB", "Abandono"),
                    ("AU", "Ausência de familiares"),
                    ("OB", "Óbito do responsável"),
                    ("MU", "Mudança de endereço"),
                    ("OU", "Outro"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="n_bdc",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="n_cns",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="n_de_comodos",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="n_nis",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="naturalidade_estado",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapá"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PB", "Paraíba"),
                    ("PR", "Paraná"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantins"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="naturalidade_municipio",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="nome_do_responsavel",
            field=models.CharField(
                help_text="Insira o nome do responsável", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="ocupacao",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="pai",
            field=models.CharField(
                help_text="Insira o nome do pai", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="parcela1_13",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="parcela2_13",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="pessoa_com_deficiencia",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="ponto_de_referencia",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="possui_convenio_medico",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="profissao",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="qual_auxilio",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="qual_convenio",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="recebe_13_salario",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="recebe_beneficio_de_prestacao_continuada",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NR", "Não Recebe"),
                    ("SI", "Sim, Idoso"),
                    ("SP", "Sim, Pessoa com deficiência"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="recebe_programa_de_transferencia_de_renda",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NR", "Não Recebe"),
                    ("SB", "Sim, BPC"),
                    ("BF", "Sim, Bolsa Família"),
                    ("SL", "Sim, LOAS"),
                    ("SO", "Sim, Outros"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="rg",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="rg_emissao",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="rg_orgao_emissor",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="hospede",
            name="rg_uf",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AC", "Acre"),
                    ("AL", "Alagoas"),
                    ("AP", "Amapá"),
                    ("AM", "Amazonas"),
                    ("BA", "Bahia"),
                    ("CE", "Ceará"),
                    ("DF", "Distrito Federal"),
                    ("ES", "Espírito Santo"),
                    ("GO", "Goiás"),
                    ("MA", "Maranhão"),
                    ("MT", "Mato Grosso"),
                    ("MS", "Mato Grosso do Sul"),
                    ("MG", "Minas Gerais"),
                    ("PA", "Pará"),
                    ("PB", "Paraíba"),
                    ("PR", "Paraná"),
                    ("PE", "Pernambuco"),
                    ("PI", "Piauí"),
                    ("RJ", "Rio de Janeiro"),
                    ("RN", "Rio Grande do Norte"),
                    ("RS", "Rio Grande do Sul"),
                    ("RO", "Rondônia"),
                    ("RR", "Roraima"),
                    ("SC", "Santa Catarina"),
                    ("SP", "São Paulo"),
                    ("SE", "Sergipe"),
                    ("TO", "Tocantins"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="situacao_habitacional",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CO", "Cortiço"),
                    ("FA", "Favela"),
                    ("LI", "Loteamento Irregular"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="telefone_celular",
            field=models.CharField(
                blank=True,
                help_text="Formato: (00)00000-0000",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="telefone_outro",
            field=models.CharField(
                blank=True,
                help_text="Formato: (00)00000-0000",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="telefone_residencial",
            field=models.CharField(
                blank=True,
                help_text="Formato: (00)00000-0000",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="tipo_de_construcao",
            field=models.CharField(
                blank=True,
                choices=[("AL", "Alvenaria"), ("MA", "Madeira"), ("MI", "Mista")],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hospede",
            name="valor_aluguel_ou_financiamento",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
