# Generated by Django 4.1.1 on 2022-09-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betel", "0004_hospede_assistente_social_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hospede",
            name="mae",
            field=models.CharField(
                blank=True, help_text="Insira o nome da mãe", max_length=50, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hospede",
            name="nome_do_responsavel",
            field=models.CharField(
                blank=True,
                help_text="Insira o nome do responsável",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hospede",
            name="pai",
            field=models.CharField(
                blank=True, help_text="Insira o nome do pai", max_length=50, null=True
            ),
        ),
    ]
