# Generated by Django 4.1.1 on 2022-09-30 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betel", "0005_alter_hospede_mae_alter_hospede_nome_do_responsavel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familiar",
            name="nome",
            field=models.CharField(
                blank=True,
                help_text="Insira o nome do hóspede",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="familiar",
            name="parentesco_vinculo",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
