# Generated by Django 4.1.1 on 2022-09-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betel", "0006_alter_familiar_nome_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="familiar", name="estuda", field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="familiar",
            name="fatores_de_risco_social",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="familiar",
            name="grau_de_instrucao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EFI", "Ensino Fundamental Incompleto"),
                    ("EFC", "Ensino Fundamental Completo"),
                    ("EMI", "Ensino Médio Incompleto"),
                    ("EMC", "Ensino Médio Completo"),
                    ("ESI", "Ensino Superior Incompleto"),
                    ("ESC", "Ensino Superior Completo"),
                ],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="familiar",
            name="inserido_em_cedesp",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="familiar",
            name="inserido_em_ilpi",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="familiar",
            name="inserido_em_nci",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="familiar",
            name="ocupacao",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="familiar",
            name="profissao",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="familiar",
            name="renda",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="familiar",
            name="nome",
            field=models.CharField(
                blank=True,
                help_text="Insira o nome do familiar",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="hospede",
            name="parcela1_13",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hospede",
            name="parcela2_13",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="hospede",
            name="valor_aluguel_ou_financiamento",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
