# Generated by Django 4.1.1 on 2022-10-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0007_familiar_estuda_familiar_fatores_de_risco_social_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fator_de_Risco_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='familiar',
            name='fatores_de_risco_social',
        ),
        migrations.AddField(
            model_name='familiar',
            name='fatores_de_risco_social',
            field=models.ManyToManyField(help_text='Selecione os fatores de risco', to='betel.fator_de_risco_social'),
        ),
    ]
