# Generated by Django 4.1.1 on 2022-10-02 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0008_fator_de_risco_social_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospede',
            old_name='n_cns',
            new_name='n_cns_sus',
        ),
        migrations.AddField(
            model_name='hospede',
            name='procedencia',
            field=models.CharField(blank=True, choices=[('CA', 'Casa'), ('HO', 'Hospital'), ('LI', 'Lar de Idosos'), ('OU', 'Outro')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Anotacao_de_Enfermagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('anotacao', models.CharField(blank=True, max_length=255, null=True)),
                ('resposavel', models.CharField(blank=True, help_text='Insira o nome do responsável', max_length=50, null=True)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betel.hospede')),
            ],
        ),
    ]
