# Generated by Django 4.1.1 on 2022-10-02 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0009_rename_n_cns_hospede_n_cns_sus_hospede_procedencia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anotacao_de_enfermagem',
            old_name='resposavel',
            new_name='responsavel',
        ),
    ]
