# Generated by Django 4.1.1 on 2022-10-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0010_rename_resposavel_anotacao_de_enfermagem_responsavel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anotacao_de_enfermagem',
            old_name='data',
            new_name='data_hora',
        ),
    ]
