# Generated by Django 4.1.1 on 2022-10-02 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0011_rename_data_anotacao_de_enfermagem_data_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sinais_Vitais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(blank=True, null=True)),
                ('pa', models.CharField(blank=True, max_length=20, null=True)),
                ('pulso', models.CharField(blank=True, max_length=20, null=True)),
                ('resp', models.CharField(blank=True, max_length=20, null=True)),
                ('temp', models.CharField(blank=True, max_length=20, null=True)),
                ('sat', models.CharField(blank=True, max_length=20, null=True)),
                ('diures', models.CharField(blank=True, max_length=20, null=True)),
                ('evacuacao', models.CharField(blank=True, max_length=20, null=True)),
                ('responsavel', models.CharField(blank=True, help_text='Insira o nome do responsável', max_length=50, null=True)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betel.hospede')),
            ],
        ),
    ]
