# Generated by Django 4.1.1 on 2022-10-02 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0013_controle_de_dextro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evolucao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(blank=True, null=True)),
                ('tipo_de_evolucao', models.CharField(blank=True, choices=[('EN', 'Enfermagem'), ('FI', 'Fisioterapeutica'), ('NU', 'Nutrição'), ('ME', 'Médica')], max_length=2, null=True)),
                ('evolucao', models.CharField(blank=True, max_length=500, null=True)),
                ('responsavel', models.CharField(blank=True, help_text='Insira o nome do responsável', max_length=50, null=True)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betel.hospede')),
            ],
        ),
    ]
