# Generated by Django 4.1.1 on 2022-10-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0017_prescricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Insira o nome', max_length=50, null=True)),
                ('data_de_nascimento', models.DateField(blank=True, null=True)),
                ('profissao', models.CharField(blank=True, max_length=20, null=True)),
                ('jornada', models.CharField(blank=True, choices=[('12/36', '12h por 36h'), ('6/1', '6d por 1d'), ('NI', 'Não informado')], max_length=5, null=True)),
                ('endereco_rua', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_numero', models.PositiveIntegerField(blank=True, null=True)),
                ('endereco_complemento', models.CharField(blank=True, max_length=10, null=True)),
                ('endereco_cep', models.CharField(blank=True, help_text='Formato: 00000-000', max_length=9, null=True)),
                ('endereco_bairro', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco_distrito', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone_residencial', models.CharField(blank=True, help_text='Formato: (00)00000-0000', max_length=20, null=True)),
                ('telefone_celular', models.CharField(blank=True, help_text='Formato: (00)00000-0000', max_length=20, null=True)),
                ('telefone_outro', models.CharField(blank=True, help_text='Formato: (00)00000-0000', max_length=20, null=True)),
            ],
        ),
    ]
