# Generated by Django 4.1.1 on 2022-10-02 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0018_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacao_de_enfermagem',
            name='responsavel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='betel.equipe'),
            preserve_default=False,
        ),
    ]
