# Generated by Django 4.1.1 on 2022-10-02 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0019_alter_anotacao_de_enfermagem_responsavel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacao_de_enfermagem',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='betel.equipe'),
        ),
    ]
