# Generated by Django 4.1.1 on 2022-10-02 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0022_alter_evolucao_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescricao',
            name='enfermeiro_responsavel',
        ),
        migrations.AlterField(
            model_name='prescricao',
            name='medico_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='betel.equipe'),
        ),
    ]
