# Generated by Django 4.1.1 on 2022-10-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0023_remove_prescricao_enfermeiro_responsavel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sinais_vitais',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='betel.equipe'),
        ),
    ]
