# Generated by Django 4.1.1 on 2022-10-04 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("betel", "0024_alter_sinais_vitais_responsavel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enfermidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="hospede",
            name="motivo_da_hospedagem",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AB", "Abandono"),
                    ("AU", "Ausência de familiares"),
                    ("OB", "Óbito do responsável"),
                    ("MU", "Mudança de endereço"),
                    ("PR", "Procura por um cuidado especializado e focado no idoso"),
                    ("CO", "Conflito e desgaste familiar"),
                    ("OJ", "Ordem Judicial"),
                    ("OP", "Opção própria do paciente"),
                    ("OU", "Outro"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Ficha_de_Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alergia_medicamentosa", models.BooleanField(null=True)),
                (
                    "qual_alergia_med",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("internacoes_hospitalares", models.BooleanField(null=True)),
                ("data_da_ultima_internacao", models.DateField(blank=True, null=True)),
                (
                    "duracao_da_internacao",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "motivacao_da_internacao",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ja_sofreu_quedas", models.BooleanField(null=True)),
                ("ja_teve_fraturas", models.BooleanField(null=True)),
                (
                    "fratura_ha_quanto_tempo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "fratura_regiao_acometida",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("ja_foi_submetido_a_cirurgias", models.BooleanField(null=True)),
                (
                    "qual_cirurgia",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sindrome_respiratoria_aguda", models.BooleanField(null=True)),
                ("sra_quando", models.CharField(blank=True, max_length=50, null=True)),
                ("sra_se_curou_totalmente", models.BooleanField(null=True)),
                (
                    "sra_complicacoes",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("vacinado_contra_covid", models.BooleanField(null=True)),
                (
                    "vias_de_alimentacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ORA", "Oral"),
                            ("SNG", "SNG"),
                            ("SNE", "SNE"),
                            ("PAR", "Parenteral"),
                            ("JEJ", "Jejunostomia"),
                            ("GAS", "Gastrostomia"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "alteracoes_orais",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("UPD", "Uso de prótese dentária"),
                            ("DED", "Dificuldade em deglutir"),
                            ("DEM", "Dificuldade em mastigar"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "tipo_de_alimentacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SO", "Sólida"),
                            ("PA", "Pastosa"),
                            ("SE", "Semilíquida"),
                            ("LI", "Líquida"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "uso_de_tecnicas_assistivas_canudinho_espessante",
                    models.BooleanField(null=True),
                ),
                ("perda_de_peso_nos_ultimos_3meses", models.BooleanField(null=True)),
                (
                    "quanto_perdeu",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("alergia_alimentar", models.BooleanField(null=True)),
                (
                    "qual_alergia_ali",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "preferencia_alimentar",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "restricao_alimentar",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "via_de_eliminacao_intestinal",
                    models.CharField(
                        blank=True,
                        choices=[("N", "Normal"), ("F", "Fralda")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "via_de_eliminacao_urinaria",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ESP", "Espontânea"),
                            ("SVD", "SVD"),
                            ("SVA", "SVA"),
                            ("FRA", "Fralda"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("incontinencia_urinaria", models.BooleanField(null=True)),
                (
                    "pressao_arterial",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("saturacao", models.CharField(blank=True, max_length=20, null=True)),
                ("temperatura", models.CharField(blank=True, max_length=20, null=True)),
                ("pulso", models.CharField(blank=True, max_length=20, null=True)),
                ("fr", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "oxigenacao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ESP", "Espontânea"),
                            ("CAT", "Oxigenioterapia -> Cateter Nasal"),
                            ("TRA", "Oxigenioterapia -> Traqueostomia"),
                            ("MAS", "Oxigenioterapia -> Máscara de O2"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "estado_geral",
                    models.CharField(
                        blank=True,
                        choices=[("BOM", "Bom"), ("REG", "Regular"), ("MAU", "Mau")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "nivel_de_consciencia",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("CON", "Consciente"),
                            ("INC", "Inconsciente"),
                            ("PPC", "Perda parcial - confuso"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "palidez",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COR", "Corado"),
                            ("HIP", "Hipercorado"),
                            ("DES", "Descorado"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "hidratacao",
                    models.CharField(
                        blank=True,
                        choices=[("HID", "Hidratado"), ("DES", "Desidratado")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "ictericia",
                    models.CharField(
                        blank=True,
                        choices=[("ANI", "Anictérico"), ("ICT", "Ictérico")],
                        max_length=3,
                        null=True,
                    ),
                ),
                (
                    "cianose",
                    models.CharField(
                        blank=True,
                        choices=[("ACI", "Acianótico"), ("CIA", "Cianótico")],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("tabagismo", models.BooleanField(null=True)),
                ("alcoolismo", models.BooleanField(null=True)),
                ("outras_drogas", models.BooleanField(null=True)),
                (
                    "enfermidade",
                    models.ManyToManyField(
                        help_text="Selecione as enfermidades", to="betel.enfermidade"
                    ),
                ),
                (
                    "hospede",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="betel.hospede"
                    ),
                ),
            ],
        ),
    ]
