# Generated by Django 4.1.1 on 2022-10-04 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("betel", "0025_enfermidade_alter_hospede_motivo_da_hospedagem_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ficha_de_avaliacao", old_name="fr", new_name="FR",
        ),
        migrations.RenameField(
            model_name="ficha_de_avaliacao",
            old_name="sra_se_curou_totalmente",
            new_name="SRA_se_curou_totalmente",
        ),
        migrations.RenameField(
            model_name="ficha_de_avaliacao",
            old_name="qual_alergia_ali",
            new_name="qual_alergia_alimentar",
        ),
    ]
