# Generated by Django 4.1.1 on 2022-10-07 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0028_ficha_de_avaliacao_altura_ficha_de_avaliacao_apetite_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(blank=True, null=True)),
                ('hospede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betel.hospede')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betel.item')),
            ],
        ),
    ]
