# Generated by Django 4.1.1 on 2022-10-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0029_item_estoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anotacao_de_enfermagem',
            options={'ordering': ['hospede', 'data_hora'], 'verbose_name_plural': 'Anotações de Enfermagem'},
        ),
        migrations.AlterModelOptions(
            name='controle_de_dextro',
            options={'ordering': ['hospede', 'data_hora'], 'verbose_name_plural': 'Controle de Dextro'},
        ),
        migrations.AlterModelOptions(
            name='equipe',
            options={'ordering': ['nome'], 'verbose_name_plural': 'Equipe'},
        ),
        migrations.AlterModelOptions(
            name='evolucao',
            options={'ordering': ['hospede', 'tipo_de_evolucao', 'data_hora'], 'verbose_name_plural': 'Evoluções'},
        ),
        migrations.AlterModelOptions(
            name='familiar',
            options={'ordering': ['hospede', 'nome'], 'verbose_name_plural': 'familiares'},
        ),
        migrations.AlterModelOptions(
            name='fator_de_risco_social',
            options={'verbose_name_plural': 'Fatores de risco social'},
        ),
        migrations.AlterModelOptions(
            name='ficha_de_avaliacao',
            options={'ordering': ['hospede'], 'verbose_name_plural': 'Fichas de Avaliação'},
        ),
        migrations.AlterModelOptions(
            name='hospede',
            options={'ordering': ['nome_do_hospede'], 'verbose_name_plural': 'hóspedes'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='medicacao',
            options={'verbose_name_plural': 'Medicações'},
        ),
        migrations.AlterModelOptions(
            name='prescricao',
            options={'ordering': ['hospede', 'horario', 'medicacao'], 'verbose_name_plural': 'Prescrições'},
        ),
        migrations.AlterModelOptions(
            name='sinais_vitais',
            options={'ordering': ['hospede', 'data_hora'], 'verbose_name_plural': 'Sinais Vitais'},
        ),
    ]
