# Generated by Django 4.1.1 on 2022-10-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0030_alter_anotacao_de_enfermagem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fatores_de_risco_social',
            field=models.ManyToManyField(blank=True, help_text='Selecione os fatores de risco', to='betel.fator_de_risco_social'),
        ),
        migrations.AlterField(
            model_name='ficha_de_avaliacao',
            name='enfermidade',
            field=models.ManyToManyField(blank=True, help_text='Selecione as enfermidades', to='betel.enfermidade'),
        ),
    ]
