# Generated by Django 4.1.1 on 2022-10-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0032_alter_estoque_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anotacao_de_enfermagem',
            name='data_hora',
            field=models.DateTimeField(blank=True, help_text='Formato: AAAA-MM-DD HH:MM', null=True),
        ),
        migrations.AlterField(
            model_name='controle_de_dextro',
            name='data_hora',
            field=models.DateTimeField(blank=True, help_text='Formato: AAAA-MM-DD HH:MM', null=True),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='data_de_nascimento',
            field=models.DateField(blank=True, help_text='Formato: AAAA-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='evolucao',
            name='data_hora',
            field=models.DateTimeField(blank=True, help_text='Formato: AAAA-MM-DD HH:MM', null=True),
        ),
        migrations.AlterField(
            model_name='familiar',
            name='data_de_nascimento',
            field=models.DateField(blank=True, help_text='Formato: AAAA-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='ficha_de_avaliacao',
            name='data_da_ultima_internacao',
            field=models.DateField(blank=True, help_text='Formato: AAAA-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='hospede',
            name='data_de_admissao',
            field=models.DateField(blank=True, help_text='Formato: AAAA-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='prescricao',
            name='horario',
            field=models.TimeField(blank=True, help_text='Formato: HH:MM', null=True),
        ),
        migrations.AlterField(
            model_name='sinais_vitais',
            name='data_hora',
            field=models.DateTimeField(blank=True, help_text='Formato: AAAA-MM-DD HH:MM', null=True),
        ),
    ]
