# Generated by Django 4.1.1 on 2022-10-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("betel", "0033_alter_anotacao_de_enfermagem_data_hora_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evolucao",
            name="tipo_de_evolucao",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EN", "Enfermagem"),
                    ("FI", "Fisioterapêutica"),
                    ("NU", "Nutrição"),
                    ("ME", "Médica"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ficha_de_avaliacao",
            name="sono_e_repouso",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NTI", "Não tem insônia"),
                    ("DCS", "Apresenta dificuldade em conciliar o sono"),
                    ("AVV", "Acorda várias vezes"),
                    ("SON", "Sonolência"),
                    ("DDD", "Dorme durante o dia"),
                    ("TIO", "Tem insônia em outro local"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
