# Generated by Django 4.1.1 on 2022-11-17 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0035_hospede_quarto_alter_hospede_n_cns_sus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controle_de_dextro',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sinais_vitais',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
