# Generated by Django 4.1.1 on 2022-11-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('betel', '0036_controle_de_dextro_observacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='familiar',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ficha_de_avaliacao',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hospede',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='prescricao',
            name='observacao',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
